### ISSUE TITLE
Define the message structure between backend and frontend

### ISSUE THREAD

**Issue by eperinan** [frees-io/freestyle-microservices#8]
After decide how we are going to connect backend and frontend in the issue #7, we need to define the structure of the message that the backend will send to the frontend.

After it, we will create a mock to provide mock data to the frontend.

**Comment by eperinan** [comment]
The message structure decided with @calvellido between backend and frontend is going to be the following:

```scala
case class Metric[T](metric: String, microservice: String, value: T, date: Long) {
  override def toString(): String      = s"$microservice $date $metric $value"
  def toBinaryMessage(): BinaryMessage = BinaryMessage(ByteString(this.toString()))
}
```

We are going to send the message in Binary through websocket, so in the client, we will have to get the Blob and access to the fields that we are sending.

Do you agree with this approach @calvellido ?

**Comment by calvellido** [comment]
Are we gonna use protobuf for the communication between backend and frontend?

**Comment by eperinan** [comment]
In this first approach, I am going to send the messages binary without protocol buffer.

Please confirm that it fits good for you, and move to done this issue
